### ISSUE TITLE
OpenCV 4.5.5.62无法加载网络

### ISSUE THREAD

**Issue by Qian-at-DNV** [hpc203/YOLOP-opencv-dnn#6]
[ERROR:0@0.300] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Clip]:(598) from domain='ai.onnx'
Traceback (most recent call last):
  File "C:\Users\QIAWEI\OneDrive - DNV\Projects\YOLOP-opencv-dnn\main.py", line 150, in <module>
    yolonet = yolop(confThreshold=args.confThreshold, nmsThreshold=args.nmsThreshold, objThreshold=args.objThreshold)
  File "C:\Users\QIAWEI\OneDrive - DNV\Projects\YOLOP-opencv-dnn\main.py", line 19, in __init__
    self.net = cv2.dnn.readNet('yolop.onnx')
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
> Node [Clip@ai.onnx]:(598) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1613: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v20211220::ONNXImporter::parseClip(class cv::dnn::dnn4_v20211220::LayerParams &,const class opencv_onnx::NodeProto &)'
> >  (expected: 'node_proto.input_size() == 1'), where
> >     'node_proto.input_size()' is 3
> > must be equal to
> >     '1' is 1
>

**Comment by Qian-at-DNV** [comment]
Solved by installing opencv version 4.5.3.56.
