### ISSUE TITLE
请问好像Python3.8.6运行有问题还是其它问题？

### ISSUE THREAD

**Issue by 13501714030** [hpc203/YOLOP-opencv-dnn#7]
[ERROR:0@0.582] global D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp (909) cv::dnn::dnn4_v20211220::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 o
utputs: [Clip]:(598) from domain='ai.onnx'
Traceback (most recent call last):
  File "e:/MachineVision/OpenCV/_Python/YOLOP-opencv-dnn-traffic/main.py", line 152, in <module>
    yolonet = yolop(confThreshold=args.confThreshold, nmsThreshold=args.nmsThreshold, objThreshold=args.objThreshold)
  File "e:/MachineVision/OpenCV/_Python/YOLOP-opencv-dnn-traffic/main.py", line 21, in __init__
    self.net = cv2.dnn.readNet(Path+'yolop.onnx')
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:928: error: (-2:Unspecified error) in function 'cv::dnn::dnn4_v20211220::ONNXImporter::handleNode'
> Node [Clip@ai.onnx]:(598) parse error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:1613: error: (-2:Unspecified error) in function 'void __cdecl cv::dnn::dnn4_v2021122
0::ONNXImporter::parseClip(class cv::dnn::dnn4_v20211220::LayerParams &,const class opencv_onnx::NodeProto &)'
> >  (expected: 'node_proto.input_size() == 1'), where
> >     'node_proto.input_size()' is 3
> > must be equal to
> >     '1' is 1

**Comment by Rachel-liuqr** [comment]
我使用的opencv4.5.5 C++版本也遇到这个问题，不知道你解决了吗

**Comment by hs7251912** [comment]
报错的原因：是opencv不能加载yolop模型中的Focus模块，
修改方法：按照blog中的方法修改就行：https://blog.csdn.net/nihate/article/details/112731327
